/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"

/* Header for class com_manouti_eardetection_EarDetection */

using namespace cv;

#ifndef _Included_com_manouti_eardetection_EarDetection
#define _Included_com_manouti_eardetection_EarDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_manouti_eardetection_EarDetection
 * Method:    earDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_manouti_eardetection_EarDetection_earDetection
  (JNIEnv *, jclass, jlong);

void earDetect(Mat& );

#ifdef __cplusplus
}
#endif
#endif
